version: '3'
services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
      - "8081:8081"
      - "8001:8001"
      - "8082:8082"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
