version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-mcp-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./sessions.json:/app/sessions.json
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - LOG_FILE=/app/logs/api.log
    command: python server.py --host=0.0.0.0 --port=8000
